--Agregado que representa o total gasto em transferências por time anualmente

use projeto_football_scouting

CREATE TABLE FATO_TRANSFERENCIA_TIME_ANUAL (
    ID_TEMPO BIGINT NOT NULL,
    ID_TIME INT NOT NULL,
    ANO INT NOT NULL,
    TOTAL_GASTO DECIMAL(18,2) NOT NULL,
    CONSTRAINT FK_DIM_TEMPO_ANUAL FOREIGN KEY (ID_TEMPO) REFERENCES DIM_TEMPO (ID_TEMPO),
    CONSTRAINT FK_DIM_TIME_ANUAL FOREIGN KEY (ID_TIME) REFERENCES DIM_TIME (ID_TIME)
)

CREATE INDEX IX_FATO_TRANSFERENCIA_TIME_ANUAL_TEMPO ON FATO_TRANSFERENCIA_TIME_ANUAL (ID_TEMPO)
CREATE INDEX IX_FATO_TRANSFERENCIA_TIME_ANUAL_TIME ON FATO_TRANSFERENCIA_TIME_ANUAL(ID_TIME)


--Procedimento para o povoamento da tabela de agregado
CREATE OR ALTER PROCEDURE sp_fato_transferencia_time_anual
AS
BEGIN
    DROP TABLE IF EXISTS FATO_TRANSFERENCIA_TIME_ANUAL

    CREATE TABLE FATO_TRANSFERENCIA_TIME_ANUAL (
        ID_TEMPO BIGINT NOT NULL,
        ID_TIME INT NOT NULL,
        ANO INT NOT NULL,
        TOTAL_GASTO DECIMAL(18,2) NOT NULL,
        CONSTRAINT FK_DIM_TEMPO_ANUAL FOREIGN KEY (ID_TEMPO) REFERENCES DIM_TEMPO (ID_TEMPO),
        CONSTRAINT FK_DIM_TIME_ANUAL FOREIGN KEY (ID_TIME) REFERENCES DIM_TIME (ID_TIME)
    )

    DECLARE @ano_inicial INT = (SELECT MIN(ANO) FROM DIM_TEMPO)
    DECLARE @ano_final INT = (SELECT MAX(ANO) FROM DIM_TEMPO)
    DECLARE @id_tempo BIGINT

    WHILE(@ano_inicial <= @ano_final)
    BEGIN
        SET @id_tempo = (SELECT ID_TEMPO FROM DIM_TEMPO WHERE NIVEL = 'ANO' AND ANO = @ano_inicial)

        INSERT INTO FATO_TRANSFERENCIA_TIME_ANUAL (ID_TEMPO, ID_TIME, ANO, TOTAL_GASTO)
        SELECT @id_tempo, ID_TIME, @ano_inicial, ISNULL(SUM(VALOR), 0)
        FROM FATO_CONTRATACAO
        WHERE YEAR(CONVERT(DATETIME, DT_CONTRATACAO, 103)) = @ano_inicial
        GROUP BY ID_TIME

        SET @ano_inicial = @ano_inicial + 1
    END
END

exec sp_fato_transferencia_time_anual

select *from FATO_TRANSFERENCIA_TIME_ANUAL