--scripts para criação do ambiente dimensional

use projeto_football_scouting

CREATE TABLE DIM_LIGA (
	ID_LIGA INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
    COD_LIGA VARCHAR(10) NOT NULL,
    LIGA VARCHAR(50) NOT NULL,
    PAIS VARCHAR(50) NOT NULL,
    NR_CLUBS INT NOT NULL,
    VALOR_MERCADO VARCHAR(50) NOT NULL,
	MEDIA_VALOR_MERCADO VARCHAR(50) NOT NULL,
    CONFERENCIA VARCHAR(50) NOT NULL
)

ALTER TABLE DIM_LIGA
ALTER COLUMN VALOR_MERCADO DECIMAL(18,2) NOT NULL

CREATE TABLE DIM_TIME (
	ID_TIME INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
    COD_TIME INT NOT NULL,
    NOME_TIME VARCHAR(100) NOT NULL,
    PAIS VARCHAR(100) NOT NULL,
    NR_JOGADORES INT NOT NULL,
    VALOR_MERCADO VARCHAR(50) NOT NULL,
    COD_LIGA VARCHAR(10) NOT NULL
)

ALTER TABLE DIM_TIME
ALTER COLUMN VALOR_MERCADO DECIMAL(18,2) NOT NULL

CREATE TABLE DIM_JOGADOR (
	ID_JOGADOR INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
    COD_JOGADOR INT NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    DT_NASCIMENTO VARCHAR(50) NOT NULL,
    ALTURA VARCHAR(20) NOT NULL,
    NACIONALIDADE VARCHAR(50) NOT NULL,
    PE_BOM VARCHAR(20) NOT NULL,
	POSICAO VARCHAR(50) NOT NULL,
    VALOR_DE_MERCADO VARCHAR(50) NOT NULL,
    COD_TIME INT NULL,
    COD_STATS INT NOT NULL
)

ALTER TABLE DIM_JOGADOR
ALTER COLUMN DT_NASCIMENTO DATETIME NOT NULL
ALTER TABLE DIM_JOGADOR
ALTER COLUMN ALTURA DECIMAL(10,2) NOT NULL
ALTER TABLE DIM_JOGADOR
ALTER COLUMN VALOR_DE_MERCADO DECIMAL(18,2) NOT NULL
ALTER TABLE DIM_JOGADOR
DROP COLUMN COD_STATS

CREATE TABLE DIM_TEMPO ( 
	ID_TEMPO BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY, 
	NIVEL VARCHAR(8) NOT NULL CHECK (NIVEL IN ('DIA','MES','ANO')),
	DATA DATETIME NULL, 
	DIA INT NULL, 
	DIA_SEMANA VARCHAR(50) NULL, 
	FIM_SEMANA VARCHAR(3) NULL CHECK (FIM_SEMANA IN ('SIM','NAO')),
	FERIADO VARCHAR(100) NULL, 
	FL_FERIADO VARCHAR(3) NULL CHECK (FL_FERIADO IN ('SIM','NAO')),
	MES INT NULL, 
	NOME_MES VARCHAR(100) NULL, 
	TRIMESTRE INT NULL, 
	NOME_TRIMESTRE VARCHAR(100) NULL, 
	SEMESTRE INT NULL, 
	NOME_SEMESTRE VARCHAR(100) NULL, 
	ANO INT NOT NULL 
) 

CREATE INDEX IX_DIM_TEMPO_DATA ON DIM_TEMPO (DATA) 
CREATE INDEX IX_DIM_TEMPO_DATA_MES ON DIM_TEMPO (NIVEL, MES) 
CREATE INDEX IX_DIM_TEMPO_DATA_ANO ON DIM_TEMPO (NIVEL, ANO)

CREATE TABLE FATO_CONTRATACAO (
	ID_CONTRATACAO BIGINT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	ID_TIME INT NOT NULL,
	ID_LIGA INT NOT NULL,
	ID_JOGADOR INT NOT NULL,
	ID_TEMPO BIGINT NOT NULL,
    COD_CONTRATACAO INT NOT NULL,
    VALOR VARCHAR(50) NOT NULL,
    DT_CONTRATACAO VARCHAR(50) NOT NULL,
	TIME_ORIGEM VARCHAR(100) NOT NULL,
	TIME_DESTINO VARCHAR(100) NOT NULL,
	TEMPORADA VARCHAR(50) NOT NULL,
	QUANTIDADE INT DEFAULT(1),
    COD_JOGADOR INT NOT NULL,
    COD_TIME INT NULL,
	CONSTRAINT FK_DIM_TIME FOREIGN KEY (ID_TIME) REFERENCES DIM_TIME (ID_TIME),
	CONSTRAINT FK_DIM_LIGA FOREIGN KEY (ID_LIGA) REFERENCES DIM_LIGA (ID_LIGA),
	CONSTRAINT FK_TEMPO FOREIGN KEY (ID_TEMPO) REFERENCES DIM_TEMPO (ID_TEMPO),
	CONSTRAINT FK_DIM_JOGADOR FOREIGN KEY (ID_JOGADOR) REFERENCES DIM_JOGADOR (ID_JOGADOR)
)

ALTER TABLE FATO_CONTRATACAO
ALTER COLUMN VALOR DECIMAL(18,2) NOT NULL
ALTER TABLE FATO_CONTRATACAO
ALTER COLUMN DT_CONTRATACAO DATETIME NOT NULL

CREATE TABLE FATO_STATS (
	ID_STATS INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	ID_TIME INT NOT NULL,
	ID_LIGA INT NOT NULL,
	ID_JOGADOR INT NOT NULL,
	ID_TEMPO BIGINT NOT NULL,
    COD_STATS INT NOT NULL,
    GOLS INT NOT NULL,
    ASSISTENCIAS INT NOT NULL,
    JOGOS INT NOT NULL,
    MINUTOS_JOGADOS INT NOT NULL,
    CARTOES_AMARELOS INT NOT NULL,
    CARTOES_VERMELHOS INT NOT NULL,
    CLEAN_SHEETS INT NOT NULL,
    TEMPORADA VARCHAR(20) NOT NULL,
	CONSTRAINT FK_DIM_TIME_STATS FOREIGN KEY (ID_TIME) REFERENCES DIM_TIME (ID_TIME),
	CONSTRAINT FK_DIM_LIGA_STATS FOREIGN KEY (ID_LIGA) REFERENCES DIM_LIGA (ID_LIGA),
	CONSTRAINT FK_TEMPO_STATS FOREIGN KEY (ID_TEMPO) REFERENCES DIM_TEMPO (ID_TEMPO),
	CONSTRAINT FK_DIM_JOGADOR_STATS FOREIGN KEY (ID_JOGADOR) REFERENCES DIM_JOGADOR (ID_JOGADOR)
)