--scripts para criação do ambiente operacional

use projeto_football_scouting

CREATE TABLE TB_LIGA (
    COD_LIGA VARCHAR(10) NOT NULL PRIMARY KEY,
    LIGA VARCHAR(50) NOT NULL,
    PAIS VARCHAR(50) NOT NULL,
    NR_CLUBS INT NOT NULL,
    VALOR_MERCADO VARCHAR(50) NOT NULL,
    MEDIA_VALOR_MERCADO VARCHAR(50) NOT NULL,
    CONFERENCIA VARCHAR(50) NOT NULL
)

CREATE TABLE TB_TIME (
    COD_TIME INT NOT NULL PRIMARY KEY,
    NOME_TIME VARCHAR(100) NOT NULL,
    PAIS VARCHAR(100) NOT NULL,
    NR_JOGADORES INT NOT NULL,
    VALOR_MERCADO VARCHAR(50) NOT NULL,
    COD_LIGA VARCHAR(10) NOT NULL,
    CONSTRAINT FK_TB_TIME_TB_LIGA
        FOREIGN KEY (COD_LIGA)
        REFERENCES TB_LIGA (COD_LIGA)
)

CREATE TABLE TB_JOGADOR (
    COD_JOGADOR INT NOT NULL PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    DT_NASCIMENTO VARCHAR(50) NOT NULL,
    ALTURA VARCHAR(20) NOT NULL,
    NACIONALIDADE VARCHAR(50) NOT NULL,
    PE_BOM VARCHAR(20) NOT NULL,
    POSICAO VARCHAR(50) NOT NULL,
    VALOR_DE_MERCADO VARCHAR(50) NOT NULL,
    COD_TIME INT NULL,
    CONSTRAINT FK_TB_JOGADOR_TB_TIME
        FOREIGN KEY (COD_TIME)
        REFERENCES TB_TIME (COD_TIME),
)

CREATE TABLE TB_CONTRATACAO (
    COD_CONTRATACAO INT NOT NULL PRIMARY KEY,
    VALOR VARCHAR(50) NOT NULL,
    DT_CONTRATACAO VARCHAR(50) NOT NULL,
    TIME_ORIGEM VARCHAR(100) NOT NULL,
    TIME_DESTINO VARCHAR(100) NOT NULL,
    TEMPORADA VARCHAR(50) NOT NULL,
    COD_JOGADOR INT NOT NULL,
    COD_TIME INT NULL,
    CONSTRAINT FK_TB_JOGADOR_TB_CONTRATACAO
        FOREIGN KEY (COD_JOGADOR)
        REFERENCES TB_JOGADOR (COD_JOGADOR),
    CONSTRAINT FK_TB_TIME_TB_CONTRATACAO
        FOREIGN KEY (COD_TIME)
        REFERENCES TB_TIME (COD_TIME)
)
