--ETL para tratar dados da área de staging

use projeto_football_scouting

--ETL Ligas
CREATE OR ALTER PROCEDURE ETL_Staging_Liga
AS
BEGIN
    -- Atualizar caracteres especiais na coluna "LIGA"
    UPDATE TB_AUX_LIGA
    SET LIGA = REPLACE(LIGA, 'Ã©', 'é')

    -- Converter VALOR_DE_MERCADO para o formato desejado e extrair apenas números
    UPDATE TB_AUX_LIGA
    SET VALOR_MERCADO = 
        CASE 
            WHEN VALOR_MERCADO LIKE '%bn' THEN CAST(REPLACE(REPLACE(VALOR_MERCADO, 'â‚¬', ''), 'bn', '') AS DECIMAL(18, 2)) * 1000000000
            WHEN VALOR_MERCADO LIKE '%m' THEN CAST(REPLACE(REPLACE(VALOR_MERCADO, 'â‚¬', ''), 'm', '') AS DECIMAL(18, 2)) * 1000000
            WHEN VALOR_MERCADO LIKE '%k' THEN CAST(REPLACE(REPLACE(VALOR_MERCADO, 'â‚¬', ''), 'k', '') AS DECIMAL(18, 2)) * 1000
            ELSE CAST(REPLACE(REPLACE(VALOR_MERCADO, 'â‚¬', ''), 'bn', '') AS DECIMAL(18, 2)) * 1000 -- Caso padrão, assumindo milhar
        END

    -- Extrair apenas números da coluna VALOR_DE_MERCADO
    UPDATE TB_AUX_LIGA
    SET VALOR_MERCADO = CAST(REPLACE(REPLACE(REPLACE(VALOR_MERCADO, 'â‚¬', ''), 'bn', ''), 'm', '') AS DECIMAL(18, 2));

	UPDATE TB_AUX_LIGA
    SET MEDIA_VALOR_MERCADO = 
        CASE 
            WHEN MEDIA_VALOR_MERCADO LIKE '%bn' THEN CAST(REPLACE(REPLACE(MEDIA_VALOR_MERCADO, 'â‚¬', ''), 'bn', '') AS DECIMAL(18, 2)) * 1000000000
            WHEN MEDIA_VALOR_MERCADO LIKE '%m' THEN CAST(REPLACE(REPLACE(MEDIA_VALOR_MERCADO, 'â‚¬', ''), 'm', '') AS DECIMAL(18, 2)) * 1000000
            WHEN MEDIA_VALOR_MERCADO LIKE '%k' THEN CAST(REPLACE(REPLACE(MEDIA_VALOR_MERCADO, 'â‚¬', ''), 'k', '') AS DECIMAL(18, 2)) * 1000
            ELSE CAST(REPLACE(REPLACE(MEDIA_VALOR_MERCADO, 'â‚¬', ''), 'bn', '') AS DECIMAL(18, 2)) * 1000 -- Caso padrão, assumindo milhar
        END

    -- Extrair apenas números da coluna MEDIA_VALOR_MERCADO
    UPDATE TB_AUX_LIGA
    SET MEDIA_VALOR_MERCADO = CAST(REPLACE(REPLACE(REPLACE(MEDIA_VALOR_MERCADO, 'â‚¬', ''), 'bn', ''), 'm', '') AS DECIMAL(18, 2));
END

exec ETL_Staging_Liga

select *from TB_AUX_LIGA


--ETL Times

set language 'PORTUGUESE'

UPDATE TB_AUX_TIME
SET NOME_TIME = '1.FC Koln' WHERE COD_TIME = 3
UPDATE TB_AUX_TIME
SET NOME_TIME = 'Atlético de Madrid' WHERE COD_TIME = 13
UPDATE TB_AUX_TIME
SET NOME_TIME = 'Borussia Monchengladbach' WHERE COD_TIME = 18
UPDATE TB_AUX_TIME
SET NOME_TIME = 'Real Betis Balompié' WHERE COD_TIME = 150
UPDATE TB_AUX_TIME
SET NOME_TIME = 'Grêmio Foot-Ball Porto Alegrense' WHERE COD_TIME = 210
UPDATE TB_AUX_TIME
SET NOME_TIME = 'Clube Atlético Mineiro' WHERE COD_TIME = 330
UPDATE TB_AUX_TIME
SET NOME_TIME = 'São Paulo Futebol Clube' WHERE COD_TIME = 585
UPDATE TB_AUX_TIME
SET NOME_TIME = 'Deportivo Alavés' WHERE COD_TIME = 1108
UPDATE TB_AUX_TIME
SET NOME_TIME = 'Esporte Clube Vitória' WHERE COD_TIME = 2125
UPDATE TB_AUX_TIME
SET NOME_TIME = 'Cádiz CF' WHERE COD_TIME = 2687
UPDATE TB_AUX_TIME
SET NOME_TIME = 'UD Almería' WHERE COD_TIME = 3302
UPDATE TB_AUX_TIME
SET NOME_TIME = 'Criciúma Esporte Clube' WHERE COD_TIME = 7178
UPDATE TB_AUX_TIME
SET NOME_TIME = 'Atlético Clube Goianiense' WHERE COD_TIME = 15172
UPDATE TB_AUX_TIME
SET NOME_TIME = 'Cuiabá Esporte Clube (MT)' WHERE COD_TIME = 28022

UPDATE TB_AUX_TIME
    SET VALOR_MERCADO = 
        CASE 
            WHEN VALOR_MERCADO LIKE '%bn' THEN CAST(REPLACE(REPLACE(VALOR_MERCADO, 'â‚¬', ''), 'bn', '') AS DECIMAL(18, 2)) * 1000000000
            WHEN VALOR_MERCADO LIKE '%m' THEN CAST(REPLACE(REPLACE(VALOR_MERCADO, 'â‚¬', ''), 'm', '') AS DECIMAL(18, 2)) * 1000000
            WHEN VALOR_MERCADO LIKE '%k' THEN CAST(REPLACE(REPLACE(VALOR_MERCADO, 'â‚¬', ''), 'k', '') AS DECIMAL(18, 2)) * 1000
            ELSE CAST(REPLACE(REPLACE(VALOR_MERCADO, 'â‚¬', ''), 'bn', '') AS DECIMAL(18, 2)) * 1000 -- Caso padrão, assumindo milhar
        END

select *from TB_AUX_TIME


--ETL Jogadores
create or alter procedure ETL_Staging_Jogador
as
begin

	UPDATE TB_AUX_JOGADOR
	SET ALTURA = CAST(REPLACE(ALTURA, ',', '.') AS DECIMAL(5, 2))

	UPDATE TB_AUX_JOGADOR
    SET ALTURA = CAST(ALTURA AS DECIMAL(10, 2))

	UPDATE TB_AUX_JOGADOR
    SET VALOR_DE_MERCADO = 
        CASE 
            WHEN VALOR_DE_MERCADO LIKE '%bn' THEN CAST(REPLACE(REPLACE(VALOR_DE_MERCADO, 'â‚¬', ''), 'bn', '') AS DECIMAL(18, 2)) * 1000000000
            WHEN VALOR_DE_MERCADO LIKE '%m' THEN CAST(REPLACE(REPLACE(VALOR_DE_MERCADO, 'â‚¬', ''), 'm', '') AS DECIMAL(18, 2)) * 1000000
            WHEN VALOR_DE_MERCADO LIKE '%k' THEN CAST(REPLACE(REPLACE(VALOR_DE_MERCADO, 'â‚¬', ''), 'k', '') AS DECIMAL(18, 2)) * 1000
            ELSE CAST(REPLACE(REPLACE(VALOR_DE_MERCADO, 'â‚¬', ''), 'bn', '') AS DECIMAL(18, 2)) * 1000 -- Caso padrão, assumindo milhar
        END
end

exec ETL_Staging_Jogador

UPDATE TB_AUX_JOGADOR
SET NOME = 'Fábio' WHERE COD_JOGADOR = 22415
UPDATE TB_AUX_JOGADOR
SET NOME = 'Alexis Sánchez' WHERE COD_JOGADOR = 40433
UPDATE TB_AUX_JOGADOR
SET NOME = 'Cássio' WHERE COD_JOGADOR = 50144
UPDATE TB_AUX_JOGADOR
SET NOME = 'Ílkay Gündoğan' WHERE COD_JOGADOR = 53622
UPDATE TB_AUX_JOGADOR
SET NOME = 'Germán Cano' WHERE COD_JOGADOR = 54590
UPDATE TB_AUX_JOGADOR
SET NOME = 'Thomas Müller' WHERE COD_JOGADOR = 58358
UPDATE TB_AUX_JOGADOR
SET NOME = 'Nacho Fernández' WHERE COD_JOGADOR = 58884
UPDATE TB_AUX_JOGADOR
SET NOME = 'Adrián' WHERE COD_JOGADOR = 71271
UPDATE TB_AUX_JOGADOR
SET NOME = 'Marc-André ter Stegen' WHERE COD_JOGADOR = 74857
UPDATE TB_AUX_JOGADOR
SET NOME = 'Antonio Rudiger' WHERE COD_JOGADOR = 86202
UPDATE TB_AUX_JOGADOR
SET NOME = 'James Rodríguez' WHERE COD_JOGADOR = 88103
UPDATE TB_AUX_JOGADOR
SET NOME = 'Hakan Çalhanoglu' WHERE COD_JOGADOR = 126414
UPDATE TB_AUX_JOGADOR
SET NOME = 'Nikão' WHERE COD_JOGADOR = 149572
UPDATE TB_AUX_JOGADOR
SET NOME = 'Iñigo Martínez' WHERE COD_JOGADOR = 158863
UPDATE TB_AUX_JOGADOR
SET NOME = 'Raphaël Guerreiro' WHERE COD_JOGADOR = 170986
UPDATE TB_AUX_JOGADOR
SET NOME = 'Nathan Aké' WHERE COD_JOGADOR = 177476
UPDATE TB_AUX_JOGADOR
SET NOME = 'João Cancelo' WHERE COD_JOGADOR = 182712
UPDATE TB_AUX_JOGADOR
SET NOME = 'Leroy Sané' WHERE COD_JOGADOR = 192565
UPDATE TB_AUX_JOGADOR
SET NOME = 'Antônio Carlos' WHERE COD_JOGADOR = 207446
UPDATE TB_AUX_JOGADOR
SET NOME = 'Gustavo Gómez' WHERE COD_JOGADOR = 215390
UPDATE TB_AUX_JOGADOR
SET NOME = 'Lucas Vázquez' WHERE COD_JOGADOR = 221316
UPDATE TB_AUX_JOGADOR
SET NOME = 'Zé Rafael' WHERE COD_JOGADOR = 225432
UPDATE TB_AUX_JOGADOR
SET NOME = 'Nicolò Barella' WHERE COD_JOGADOR = 255942
UPDATE TB_AUX_JOGADOR
SET NOME = 'Rúbens Dias' WHERE COD_JOGADOR = 258004
UPDATE TB_AUX_JOGADOR
SET NOME = 'Ángel Romero' WHERE COD_JOGADOR = 262262
UPDATE TB_AUX_JOGADOR
SET NOME = 'Lucas Hernández' WHERE COD_JOGADOR = 281963
UPDATE TB_AUX_JOGADOR
SET NOME = 'Iñaki Peña' WHERE COD_JOGADOR = 283170
UPDATE TB_AUX_JOGADOR
SET NOME = 'Ousmane Dembélé' WHERE COD_JOGADOR = 288230
UPDATE TB_AUX_JOGADOR
SET NOME = 'Léo Pereira' WHERE COD_JOGADOR = 288431
UPDATE TB_AUX_JOGADOR
SET NOME = 'Otávio' WHERE COD_JOGADOR = 312314
UPDATE TB_AUX_JOGADOR
SET NOME = 'Brahim Díaz' WHERE COD_JOGADOR = 314678
UPDATE TB_AUX_JOGADOR
SET NOME = 'Caoimhín Kelleher' WHERE COD_JOGADOR = 340918
UPDATE TB_AUX_JOGADOR
SET NOME = 'Fran García' WHERE COD_JOGADOR = 341264
UPDATE TB_AUX_JOGADOR
SET NOME = 'Kylian Mbappé' WHERE COD_JOGADOR = 342229
UPDATE TB_AUX_JOGADOR
SET NOME = 'Fabián Ruiz' WHERE COD_JOGADOR = 350219
UPDATE TB_AUX_JOGADOR
SET NOME = 'Augustín Rossi' WHERE COD_JOGADOR = 352324
UPDATE TB_AUX_JOGADOR
SET NOME = 'Ibrahima Konaté' WHERE COD_JOGADOR = 357119
UPDATE TB_AUX_JOGADOR
SET NOME = 'Sergio Gómez' WHERE COD_JOGADOR = 366930
UPDATE TB_AUX_JOGADOR
SET NOME = 'Léo Ortiz' WHERE COD_JOGADOR = 374136
UPDATE TB_AUX_JOGADOR
SET NOME = 'Nicolás de la Cruz' WHERE COD_JOGADOR = 397458
UPDATE TB_AUX_JOGADOR
SET NOME = 'Éder Militão' WHERE COD_JOGADOR = 401530
UPDATE TB_AUX_JOGADOR
SET NOME = 'Lautaro Martínez' WHERE COD_JOGADOR = 406625
UPDATE TB_AUX_JOGADOR
SET NOME = 'Jules Koundé' WHERE COD_JOGADOR = 411975
UPDATE TB_AUX_JOGADOR
SET NOME = 'Aurélien Tchouaméni' WHERE COD_JOGADOR = 413112
UPDATE TB_AUX_JOGADOR
SET NOME = 'Fabrício Bruno' WHERE COD_JOGADOR = 432773
UPDATE TB_AUX_JOGADOR
SET NOME = 'Luiz Araújo' WHERE COD_JOGADOR = 435485
UPDATE TB_AUX_JOGADOR
SET NOME = 'Matías Viña' WHERE COD_JOGADOR = 439072
UPDATE TB_AUX_JOGADOR
SET NOME = 'João Félix' WHERE COD_JOGADOR = 462250
UPDATE TB_AUX_JOGADOR
SET NOME = 'Félix Torres' WHERE COD_JOGADOR = 468174
UPDATE TB_AUX_JOGADOR
SET NOME = 'Luis Díaz' WHERE COD_JOGADOR = 480692
UPDATE TB_AUX_JOGADOR
SET NOME = 'Matías Zaracho' WHERE COD_JOGADOR = 480774
UPDATE TB_AUX_JOGADOR
SET NOME = 'Michel Araújo' WHERE COD_JOGADOR = 482144
UPDATE TB_AUX_JOGADOR
SET NOME = 'Jérémy Doku' WHERE COD_JOGADOR = 486049
UPDATE TB_AUX_JOGADOR
SET NOME = 'Joaquín Piquerez' WHERE COD_JOGADOR = 496268
UPDATE TB_AUX_JOGADOR
SET NOME = 'Darwin Núñez' WHERE COD_JOGADOR = 546543
UPDATE TB_AUX_JOGADOR
SET NOME = 'Gonçalo Ramos' WHERE COD_JOGADOR = 550550
UPDATE TB_AUX_JOGADOR
SET NOME = 'Igor Vinícius' WHERE COD_JOGADOR = 552240
UPDATE TB_AUX_JOGADOR
SET NOME = 'André Silva' WHERE COD_JOGADOR = 565232
UPDATE TB_AUX_JOGADOR
SET NOME = 'Lázaro' WHERE COD_JOGADOR = 574772
UPDATE TB_AUX_JOGADOR
SET NOME = 'Julián Álvarez' WHERE COD_JOGADOR = 576024
UPDATE TB_AUX_JOGADOR
SET NOME = 'Matheus França' WHERE COD_JOGADOR = 594226
UPDATE TB_AUX_JOGADOR
SET NOME = 'Cacá' WHERE COD_JOGADOR = 603122
UPDATE TB_AUX_JOGADOR
SET NOME = 'Fermín López' WHERE COD_JOGADOR = 636703
UPDATE TB_AUX_JOGADOR
SET NOME = 'Tom Hülsmann' WHERE COD_JOGADOR = 639582
UPDATE TB_AUX_JOGADOR
SET NOME = 'Aníbal Moreno' WHERE COD_JOGADOR = 642758
UPDATE TB_AUX_JOGADOR
SET NOME = 'Piero Hincapié' WHERE COD_JOGADOR = 659813
UPDATE TB_AUX_JOGADOR
SET NOME = 'Matheus Araújo' WHERE COD_JOGADOR = 678853
UPDATE TB_AUX_JOGADOR
SET NOME = 'Richard Ríos' WHERE COD_JOGADOR = 735573
UPDATE TB_AUX_JOGADOR
SET NOME = 'André' WHERE COD_JOGADOR = 800176
UPDATE TB_AUX_JOGADOR
SET NOME = 'Warren Zaïre-Emery' WHERE COD_JOGADOR = 810092
UPDATE TB_AUX_JOGADOR
SET NOME = 'Léo Mana' WHERE COD_JOGADOR = 838387
UPDATE TB_AUX_JOGADOR
SET NOME = 'José Manuel López' WHERE COD_JOGADOR = 844797
UPDATE TB_AUX_JOGADOR
SET NOME = 'Arda Güler' WHERE COD_JOGADOR = 861410
UPDATE TB_AUX_JOGADOR
SET NOME = 'Damián Bobadilla' WHERE COD_JOGADOR = 861852
UPDATE TB_AUX_JOGADOR
SET NOME = 'Ethan Mbappé' WHERE COD_JOGADOR = 903666
UPDATE TB_AUX_JOGADOR
SET NOME = 'João Moreira' WHERE COD_JOGADOR = 929866
UPDATE TB_AUX_JOGADOR
SET NOME = 'Héctor Fort' WHERE COD_JOGADOR = 937955
UPDATE TB_AUX_JOGADOR
SET NOME = 'Matheus Gonçalves' WHERE COD_JOGADOR = 961046
UPDATE TB_AUX_JOGADOR
SET NOME = 'Pau Cubarsí' WHERE COD_JOGADOR = 962110
UPDATE TB_AUX_JOGADOR
SET NOME = 'Lelê' WHERE COD_JOGADOR = 972864
UPDATE TB_AUX_JOGADOR
SET NOME = 'Matheus Belém' WHERE COD_JOGADOR = 980825
UPDATE TB_AUX_JOGADOR
SET NOME = 'Estévão' WHERE COD_JOGADOR = 1056993
UPDATE TB_AUX_JOGADOR
SET NOME = 'Kauã Elias' WHERE COD_JOGADOR = 1119009

UPDATE TB_AUX_JOGADOR
SET NACIONALIDADE =	'Turkey, Germany' WHERE COD_JOGADOR = 126414
UPDATE TB_AUX_JOGADOR
SET NACIONALIDADE = 'Turkey' WHERE COD_JOGADOR = 861410

CREATE OR ALTER PROCEDURE sp_ConvertDateVarcharToDate
    @varcharDate VARCHAR(50),
    @finalDate DATE OUTPUT
AS
BEGIN
    DECLARE @month VARCHAR(20)
    DECLARE @numericMonth VARCHAR(2)
    DECLARE @day VARCHAR(2)
    DECLARE @year VARCHAR(4)
    DECLARE @formattedDate VARCHAR(8)

    -- Extrair o mês
    SET @month = LEFT(@varcharDate, CHARINDEX(' ', @varcharDate) - 1)

    -- Converter o mês em seu equivalente numérico
    SET @numericMonth = CASE 
                            WHEN @month = 'Jan' THEN '01'
                            WHEN @month = 'Feb' THEN '02'
                            WHEN @month = 'Mar' THEN '03'
                            WHEN @month = 'Apr' THEN '04'
                            WHEN @month = 'May' THEN '05'
                            WHEN @month = 'Jun' THEN '06'
                            WHEN @month = 'Jul' THEN '07'
                            WHEN @month = 'Aug' THEN '08'
                            WHEN @month = 'Sep' THEN '09'
                            WHEN @month = 'Oct' THEN '10'
                            WHEN @month = 'Nov' THEN '11'
                            WHEN @month = 'Dec' THEN '12'
                        END

    -- Extrair o dia
    SET @day = SUBSTRING(@varcharDate, CHARINDEX(' ', @varcharDate) + 1, CHARINDEX(',', @varcharDate) - CHARINDEX(' ', @varcharDate) - 1)

    -- Extrair o ano
    SET @year = SUBSTRING(@varcharDate, CHARINDEX(',', @varcharDate) + 2, 4)

    -- Formatar a data como yyyyMMdd
    SET @formattedDate = @year + @numericMonth + RIGHT('00' + @day, 2)

    -- Converter para DATE
    SET @finalDate = CONVERT(DATE, @formattedDate, 112)
END

CREATE OR ALTER PROCEDURE sp_Atualizar_Datas
AS
BEGIN
	DECLARE @varcharDate VARCHAR(50)
	DECLARE @finalDate DATE

	DECLARE date_cursor CURSOR FOR
	SELECT DT_NASCIMENTO
	FROM TB_AUX_JOGADOR

	OPEN date_cursor

	FETCH NEXT FROM date_cursor INTO @varcharDate

	WHILE @@FETCH_STATUS = 0
	BEGIN
		-- Chamar o procedimento para converter a data
		EXEC sp_ConvertDateVarcharToDate @varcharDate, @finalDate OUTPUT

		-- Atualizar a linha na tabela AUX_JOGADOR com a nova data
		UPDATE TB_AUX_JOGADOR
		SET DT_NASCIMENTO = @finalDate
		WHERE CURRENT OF date_cursor

		FETCH NEXT FROM date_cursor INTO @varcharDate
	END

	CLOSE date_cursor
	DEALLOCATE date_cursor
END

exec sp_Atualizar_Datas

select *from TB_AUX_JOGADOR


--ETL Contratações
UPDATE TB_AUX_CONTRATACAO
    SET VALOR = 
        CASE 
            WHEN VALOR LIKE '%bn' THEN CAST(REPLACE(REPLACE(VALOR, 'â‚¬', ''), 'bn', '') AS DECIMAL(18, 2)) * 1000000000
            WHEN VALOR LIKE '%m' THEN CAST(REPLACE(REPLACE(VALOR, 'â‚¬', ''), 'm', '') AS DECIMAL(18, 2)) * 1000000
            WHEN VALOR LIKE '%k' THEN CAST(REPLACE(REPLACE(VALOR, 'â‚¬', ''), 'k', '') AS DECIMAL(18, 2)) * 1000
            ELSE CAST(REPLACE(REPLACE(VALOR, 'â‚¬', ''), 'bn', '') AS DECIMAL(18, 2)) * 1000 -- Caso padrão, assumindo milhar
        END

UPDATE TB_AUX_CONTRATACAO
SET TIME_ORIGEM = 'Atlético-PR' WHERE COD_CONTRATACAO = 1975102
UPDATE TB_AUX_CONTRATACAO
SET TIME_ORIGEM = 'São Paulo' WHERE COD_CONTRATACAO = 4793946
UPDATE TB_AUX_CONTRATACAO
SET TIME_DESTINO = 'Atlético-PR' WHERE COD_CONTRATACAO = 719776
UPDATE TB_AUX_CONTRATACAO
SET TIME_DESTINO = 'Atlético-MG' WHERE COD_CONTRATACAO = 3227515
UPDATE TB_AUX_CONTRATACAO
SET TIME_DESTINO = 'São Paulo' WHERE COD_CONTRATACAO = 4542738

CREATE OR ALTER PROCEDURE sp_Atualizar_Datas_Contratacoes
AS
BEGIN
	DECLARE @varcharDate VARCHAR(50)
	DECLARE @finalDate DATE

	DECLARE date_cursor CURSOR FOR
	SELECT DT_CONTRATACAO
	FROM TB_AUX_CONTRATACAO

	OPEN date_cursor

	FETCH NEXT FROM date_cursor INTO @varcharDate

	WHILE @@FETCH_STATUS = 0
	BEGIN
		-- Chamar o procedimento para converter a data
		EXEC sp_ConvertDateVarcharToDate @varcharDate, @finalDate OUTPUT

		-- Atualizar a linha na tabela AUX_JOGADOR com a nova data
		UPDATE TB_AUX_CONTRATACAO
		SET DT_CONTRATACAO = @finalDate
		WHERE CURRENT OF date_cursor

		FETCH NEXT FROM date_cursor INTO @varcharDate
	END

	CLOSE date_cursor
	DEALLOCATE date_cursor
END

exec sp_Atualizar_Datas_Contratacoes

select *from TB_AUX_CONTRATACAO